/* Fuente: valsbness/Grotti-Tool, consultada el 14-09-2026. Importes del juego. */
(function(root){const catalog=[
  {
    "id": "repair",
    "category": "Mantenimiento",
    "name": "Kit de reparación",
    "cost": 500,
    "price": 1000,
    "active": true,
    "sort": 0,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "performance",
    "category": "Motor",
    "name": "Piezas de rendimiento",
    "cost": 7000,
    "price": 10000,
    "active": true,
    "sort": 1,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "paint",
    "category": "Estética",
    "name": "Kit de pintura",
    "cost": 500,
    "price": 1500,
    "active": true,
    "sort": 2,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "cosmetic",
    "category": "Estética",
    "name": "Piezas cosméticas",
    "cost": 2000,
    "price": 4000,
    "active": true,
    "sort": 3,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "rims",
    "category": "Ruedas",
    "name": "Set de rines",
    "cost": 7000,
    "price": 10000,
    "active": true,
    "sort": 4,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "smoke",
    "category": "Ruedas",
    "name": "Humo para neumáticos",
    "cost": 2500,
    "price": 10000,
    "active": true,
    "sort": 5,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "v12",
    "category": "Motor",
    "name": "Motor V12",
    "cost": 250000,
    "price": 500000,
    "active": true,
    "sort": 6,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "v8",
    "category": "Motor",
    "name": "Motor V8",
    "cost": 35000,
    "price": 50000,
    "active": true,
    "sort": 7,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "brakes",
    "category": "Frenos",
    "name": "Frenos cerámicos",
    "cost": 8000,
    "price": 25000,
    "active": true,
    "sort": 8,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "turbo",
    "category": "Motor",
    "name": "Turbo Charger",
    "cost": 25000,
    "price": 25000,
    "active": true,
    "sort": 9,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "awd",
    "category": "Tracción",
    "name": "Tracción AWD",
    "cost": 8000,
    "price": 13000,
    "active": true,
    "sort": 10,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "rwd",
    "category": "Tracción",
    "name": "Tracción RWD",
    "cost": 7000,
    "price": 12000,
    "active": true,
    "sort": 11,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "fwd",
    "category": "Tracción",
    "name": "Tracción FWD",
    "cost": 6000,
    "price": 11000,
    "active": true,
    "sort": 12,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "slick",
    "category": "Ruedas",
    "name": "Neumáticos Slick",
    "cost": 4000,
    "price": 7000,
    "active": true,
    "sort": 13,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "semi",
    "category": "Ruedas",
    "name": "Neumáticos Semi-Slick",
    "cost": 3500,
    "price": 7000,
    "active": true,
    "sort": 14,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "offroad",
    "category": "Ruedas",
    "name": "Neumáticos Offroad",
    "cost": 4500,
    "price": 7000,
    "active": true,
    "sort": 15,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "nitro",
    "category": "Motor",
    "name": "Nitro",
    "cost": 0,
    "price": 1000000,
    "active": true,
    "sort": 16,
    "description": "Coste pendiente de confirmar: la fuente lo configura en $0.",
    "cost_confirmed": false
  },
  {
    "id": "nitro-bottle",
    "category": "Motor",
    "name": "Botella de nitro",
    "cost": 0,
    "price": 200000,
    "active": true,
    "sort": 17,
    "description": "Coste pendiente de confirmar: la fuente lo configura en $0.",
    "cost_confirmed": false
  },
  {
    "id": "stance",
    "category": "Ruedas",
    "name": "Stance o suspensión",
    "cost": 35000,
    "price": 35000,
    "active": true,
    "sort": 18,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "extras",
    "category": "Estética",
    "name": "Extras",
    "cost": 4000,
    "price": 10000,
    "active": true,
    "sort": 19,
    "description": "",
    "cost_confirmed": true
  },
  {
    "id": "full-v12",
    "category": "Paquetes",
    "name": "Full Tuning V12",
    "cost": 295000,
    "price": 575000,
    "active": true,
    "sort": 20,
    "description": "V12, turbo, frenos cerámicos, Slick, AWD y servicio.",
    "cost_confirmed": false
  },
  {
    "id": "full-v8",
    "category": "Paquetes",
    "name": "Full Tuning V8",
    "cost": 79500,
    "price": 115000,
    "active": true,
    "sort": 21,
    "description": "V8, turbo, frenos cerámicos, Semi-Slick, AWD y servicio gratis. Tarifa de paquete; piezas por separado: $120,000.",
    "cost_confirmed": false
  }
];if(typeof module!=='undefined')module.exports=catalog;else root.OS_CATALOG=catalog;})(typeof window!=='undefined'?window:globalThis);
